BA-000.6 - Add and Update CONTRIBUTING.md to yna_backend [fixes #2]
Young-N-Ambitious/yna_backend pull request #3
Opened 2022-10-09 08:10 UTC by najeebkp

### BA-000.6 - Add and Update CONTRIBUTING.md to yna_backend [fixes #2]

2022-10-09 17:01 UTC, stef-codes submitted a review, later dismissed
Thank you for making these changes!

2022-10-09 17:35 UTC, Sydnee510 requested changes
hey can you address these small changes @najeebkp

2022-10-09 17:35 UTC, Sydnee510 commented on CONTRIBUTING.md
> +      5. Now run `npm install` to install all of the project dependencies.
remove` npm install` and add `bundle install`

2022-10-09 17:35 UTC, Sydnee510 commented on CONTRIBUTING.md
> +         FD-[#<issue_number>]<commit_type>-<description/name>
the branch syntax for backend should be BA-[#<issue_number>-<description/name>
**Example branch name: BA-001-enable-cors**

2022-10-09 17:35 UTC, Sydnee510 commented on CONTRIBUTING.md
> +      by running `git commit -m "FD-[#<issue_number>]<commit_type>:description"`
`git commit -m "BA-[#<issue_number>]<commit_type>:description"`

2022-10-10 03:04 UTC, najeebkp commented
changes made !

2022-10-10 04:58 UTC, Sydnee510 approved these changes
+1

2022-10-10 05:03 UTC, Sydnee510 commented
Task linked: [CU-2y49agp BA-000.2 - Create Contributor.md](https://app.clickup.com/t/2y49agp)

2022-10-10 05:14 UTC, stef-codes approved these changes
Thanks for adding this and making the changes!

2022-10-10 05:14 UTC, merged